//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wechat.Web.admin {
	
	
	public partial class company {
		
		protected System.Web.UI.WebControls.TextBox tb_company;
		
		protected System.Web.UI.WebControls.TextBox tb_login;
		
		protected System.Web.UI.WebControls.TextBox tb_pwd1;
		
		protected System.Web.UI.WebControls.TextBox tb_pwd2;
		
		protected System.Web.UI.WebControls.Button btn_sava;
	}
}
